Rewrited and updated debian scripts

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,48 +1,46 @@
 #!/bin/sh
-# postinst script for wargus
-#
-# see: dh_installdeb(1)
 
 set -e
 
-# Source debconf library
 . /usr/share/debconf/confmodule
 
-case "$1" in
-  configure)
-      db_get shared/stargusextractdata || true
-      if [ "$RET" = "true" ]; then
-        db_get shared/starguscdpath || true
-        CDPATH=${RET}
-        EXTRACTVIDEO=
-        EXTRACTMUSIC=
-        if [ -d "${CDPATH}" ]; then
-          db_get shared/stargusextractvideo || true
-          if [ ${RET} = "true" ]; then
-            EXTRACTVIDEO="-v"
-          fi
-          db_get shared/stargusextractmusic || true
-          if [ ${RET} = "true" ]; then
-            EXTRACTMUSIC="-v"
-          fi
-          echo "Extracting data from ${CDPATH} to /usr/share/games/stratagus/stargus"
-          /usr/share/games/stratagus/stargus/build.sh -p ${CDPATH} -m -b /usr/games -o /usr/share/games/stratagus/stargus -s -c ${EXTRACTVIDEO} ${EXTRACTMUSIC}
-        else
-          echo "${RET} doesn't exist - can't extract WarCraft II data" >&2
-          exit 1
-        fi
-      fi
-  ;;
-  *)
-    echo "postinst called with unknown argument \`$1'" >&2
-    exit 1
-  ;;
-esac
+extract() {
 
-db_stop || true
+	db_get stargus/extractdata || true
 
-# dh_installdeb will replace this with shell code automatically
-# generated by other debhelper scripts.
+	if [ "$RET" = "true" ]; then
+
+		db_get stargus/cdpath || true
+
+		CDPATH=${RET}
+
+		if [ -d "${CDPATH}" ]; then
+
+			db_stop || true
+			echo "Extracting data from ${CDPATH} to /usr/share/games/stratagus/stargus"
+
+			cd /usr/share/games/stratagus/stargus
+			startool ${CDPATH} /usr/share/games/stratagus/stargus
+			return $?
+
+		else
+
+			db_stop || true
+			echo "${RET} doesn't exist - can't extract Starcraft data" >&2
+			return 1
+
+		fi
+
+	fi
+
+	db_stop || true
+	return 0
+
+}
+
+if [ "$1" = "configure" ]; then
+	extract || exit $?
+fi
 
 #DEBHELPER#
 
